
/**
 * Array of words that can be chosen for the guessing game.
 * @type {string[]}
 */
export const words = ["ARGENTINA", "AUSTRALIA", "AUSTRIA", "BANGLADESH", "BELGIUM", "BRAZIL", "BULGARIA", "CANADA", 
    "CHILE", "CHINA", "COLOMBIA", "CROATIA", "CZECHIA", "DENMARK", "DOMINICA", "ECUADOR", 
    "EGYPT", "ESTONIA", "ETHIOPIA", "FINLAND", "FRANCE", "GEORGIA", "GERMANY", "GHANA", 
    "GREECE", "HUNGARY", "ICELAND", "INDIA", "INDONESIA", "IRAN", "IRAQ", "IRELAND", 
    "ISRAEL", "ITALY", "JAMAICA", "JAPAN", "JORDAN", "KENYA", "LATVIA", "LEBANON", 
    "LITHUANIA", "MALAYSIA", "MEXICO", "MOROCCO", "NEPAL", "NETHERLANDS", "NIGERIA", 
    "NORWAY", "PAKISTAN", "PERU", "PHILIPPINES", "POLAND", "PORTUGAL", "QATAR", "ROMANIA", 
    "RUSSIA", "SAUDIARABIA", "SENEGAL", "SERBIA", "SINGAPORE", "SLOVAKIA", "SLOVENIA", 
    "SOUTHAFRICA", "SOUTHKOREA", "SPAIN", "SWEDEN", "SWITZERLAND", "THAILAND", "TURKEY", 
    "UKRAINE", "UNITEDKINGDOM", "UNITEDSTATES", "URUGUAY", "VENEZUELA", "VIETNAM", "ZIMBABWE"]; 
 